web:
  image: nginx:latest
  ports:
     - "8080:80"
  volumes:
     - ./code:/code
     - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
     - php
php:
  image : mshahmi/docker-magento2-base
  volumes:
    - ./code:/code